### ISSUE TITLE
Question about the noise term and beta1

### ISSUE THREAD

**Issue by gokceneraslan** [ucla-vision/entropy-sgd#2]
Thanks for very nice algorithm and implementation. I have a question about the noise term, which reads as follows in the implementation: 

`ldfdx:add(-g, xc-lx):add(wd,lx):add(noise/math.sqrt(0.5*lclr), eta)`

but according to line 5 of `Algorithm 1` in paper, shouldn't it be:

`ldfdx:add(-g, xc-lx):add(wd,lx):add(noise*math.sqrt(lclr), eta)`

Why is noise divided by lclr and lclr is multiplied by 0.5?

Thanks a lot!

**Comment by gokceneraslan** [comment]
Another quesion is about this line:

`lmx:mul(sgld.beta1):add(1-sgld.beta1, lx)`

In order for beta1 to match alpha in Algorithm 1, this line should read:

`lmx:mul(1-sgld.beta1):add(sgld.beta1, lx)`

right? Otherwise, the implementation puts more weight to previous samples, compared to the paper which favors later samples, since beta1=alpha=0.75.

**Comment by pratikac** [comment]
Hi @gokceneraslan,

The noise term is divided by `sqrt(0.5)` only to remain consistent with the equations in the [Eqn. 4, SGLD paper](http://machinelearning.wustl.edu/mlpapers/paper_files/ICML2011Welling_398.pdf). But you are right, line 5 in Alg. 1 of our paper should have a factor of 2 if the numbers in Sec. 5.2 are used; otherwise, you'd need to divide the temperature by the same factor. That said, we have not seen the results change if one changes the temperature; it was set to `1e-4` for all the experiments in the paper, lower values also work.

Again, nice catch, the wording of the paper is inaccurate :-) We are doing exponential averaging of the SGLD iterates; so `lmx:mul(sgld.beta1):add(1-sgld.beta1, lx)` with beta1=0.75 makes sense because there are more steps in the past (this is the same intuition as [Line 45 using momentum](https://github.com/ucla-vision/entropy-sgd/blob/master/entropyoptim.lua#L45)).

**Comment by gokceneraslan** [comment]
> Hi @gokceneraslan
> 
> The noise term is divided by |sqrt(0.5)| only to remain consistent with
> the equations in the Eqn. 4, SGLD paper
> <http://machinelearning.wustl.edu/mlpapers/paper_files/ICML2011Welling_398.pdf>.
> But you are right, line 5 in Alg. 1 of our paper should have a factor of
> 2 if the numbers in Sec. 5.2 are used; otherwise, you'd need to divide
> the temperature by the same factor. That said, we have not seen the
> results change if one changes the temperature; it was set to |1e-4| for
> all the experiments in the paper, lower values also work.
> 

OK, I get the 0.5 part.

About the multiplication/division part of my question, I'm a bit
confused. Shouldn't N(0,I) be multiplied eventually by lclr so that sgld
learning rate and the variance of the noise somewhat match? But, right
now N(0,I) is divided by lclr (or sqrt of its half, to be exact)

> About the second question, again, nice catch :-) We are doing
> exponential averaging of the SGLD iterates; so
> |lmx:mul(sgld.beta1):add(1-sgld.beta1, lx)| with beta1=0.75 makes sense
> because there are more steps in the past (this is the same intuition as
> Line 45 momentum
> <https://github.com/ucla-vision/entropy-sgd/blob/master/entropyoptim.lua#L45>).

Ah, ok. Yeah, this makes sense. Thanks again for the fast reply!

**Comment by pratikac** [comment]
>
> .... right now N(0,I) is divided by lclr (or sqrt of its half, to be exact)
>

ldfdx is multiplied by lclr for the update on [Line 95](https://github.com/ucla-vision/entropy-sgd/blob/master/entropyoptim.lua#L95).

**Comment by gokceneraslan** [comment]
By the way, it doesn't make any difference as `eta` has zero mean, but following line

`add(noise/math.sqrt(0.5*lclr), eta)`

should actually read:

`add(-noise/math.sqrt(0.5*lclr), eta)`

right? So that `x' <- x' - n'dx' + sqrt(n') eps N(0,I)`. Just to make the code more similar to Algorithm 1.
